import streamlit as st

def render():
    """Renders the User Manual page in a clean, human-friendly format."""
    
    st.header("📖 User Manual: Revenue Cycle Intelligence")
    st.markdown("---")
    
    st.markdown("""
    ### 1. Introduction
    Welcome to **Revenue Cycle Intelligence**, an AI-powered analytics platform designed for Hospital CFOs and Revenue Cycle Directors. This tool bridges the gap between raw financial data and actionable executive insights by combining a high-performance KPI engine with the power of the Claude AI agent.

    ### 2. Key Modules

    #### 📈 Dashboard
    The central hub for real-time monitoring.
    - **KPI Cards**: View 12 core revenue cycle metrics. Each card shows the current value, a trend comparison vs. the previous period, and your facility's ranking in industry benchmarks (e.g., "75th percentile").
    - **Trend Charts**: Interactive charts show monthly collection rates and denial patterns.
    - **Anomaly Alerts**: Threshold-based alerts that highlight unusual spikes in denial rates or delays in A/R.
    - **AI Executive Summary**: A natural-language summary generated by Claude that interprets the raw data for you.

    #### 💬 AI Query Console
    Ask your data questions in plain English.
    - **How to use**: Type queries like *"What is our denial rate for BCBS in Q4?"* or *"Compare collections for the last two quarters."*
    - **Suggested Queries**: Use the sidebar for ideas on what to ask.

    #### ⚖️ Benchmark Comparison
    See how you stack up against the competition.
    - **Profile Config**: Set your hospital type and bed count to refine comparisons.
    - **Peer Comparison**: Compare your metrics against HFMA 2024 medians (25th, 50th, 75th, 90th percentiles).
    - **AI Gap Analysis**: Recommendations on how to bridge performance gaps and improve cash flow.

    #### 📋 Report Generator
    Produce board-ready deliverables in seconds.
    - **Selection**: Choose from curated templates like the **Board Deck**.
    - **Download**: Once the agent builds the report, download it directly to your device.

    #### ⚙️ Data Management
    Control your data source and monitor quality.
    - **Refresh**: Trigger a manual sync from your source data.
    - **Quality Report**: View validation findings and normalization status.

    ### 3. Data Specifications
    The system expects standard hospital financial records including service dates, payer names, charges, allowed amounts, and claim status.

    ### 4. Security & Privacy
    - **No PHI**: This tool is designed for aggregate financial analysis. Do not upload files containing Patient Health Information (PHI).
    - **Encryption**: All data transmissions are encrypted. Access to data management is restricted.
    
    ---
    **Support**: contact-support@revcycle-intel.com | **v1.0.0**
    """)
