from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
import os
import logging

logger = logging.getLogger(__name__)

def generate_board_deck(data: dict, output_path: str):
    """Generates a PowerPoint board deck from KPI data."""
    prs = Presentation()
    
    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "Revenue Cycle Performance Review"
    subtitle.text = f"Executive Board Deck | Q4 2025\nGenerated by RevCycle AI"

    # 2. Executive Summary
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    title_shape.text = "Executive Summary"
    
    body_shape = shapes.placeholders[1]
    tf = body_shape.text_frame
    tf.text = "Overall Performance"
    
    p = tf.add_paragraph()
    p.text = f"Net Collection Rate: {data.get('net_collection_rate', 'N/A')}%"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"Denial Rate: {data.get('denial_rate', 'N/A')}%"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = "Key Insights"
    p.level = 0
    
    p = tf.add_paragraph()
    p.text = "Commercial payers showing increased denial rates due to prior auth."
    p.level = 1

    # 3. KPI Table
    slide = prs.slides.add_slide(prs.slide_layouts[5]) # Title only
    slide.shapes.title.text = "Core KPI Metrics"
    
    rows = len(data) + 1
    cols = 2
    left = Inches(1.0)
    top = Inches(2.0)
    width = Inches(8.0)
    height = Inches(4.0)
    
    table = slide.shapes.add_table(rows, cols, left, top, width, height).table
    
    # Header
    table.cell(0, 0).text = 'Metric'
    table.cell(0, 1).text = 'Value'
    
    # Data
    for i, (k, v) in enumerate(data.items()):
        table.cell(i+1, 0).text = k.replace('_', ' ').title()
        table.cell(i+1, 1).text = str(v)

    # Save
    prs.save(output_path)
    return output_path
